<?php

namespace CrudBundle\Repository;

/**
 * femmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class femmeRepository extends \Doctrine\ORM\EntityRepository
{
}
