<?php

namespace CrudBundle\Repository;

/**
 * hommeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hommeRepository extends \Doctrine\ORM\EntityRepository
{
}
